apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: pubsub
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: catpaladin/consumer@sha256:7a29f53811c0a9e34347adb0594f6b4712ccbae1235ca64e4b4f8299ab0aa72a
        command: ["sh", "-c", "tail -f /dev/null"]
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 10m
            memory: 200Mi
        env:
          - name: KAFKA_HOST
            value: bootstrap.kafka
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_TOPIC
            value: banana
