# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: kafka
spec:
  ports:
  - port: 9094
    protocol: TCP
    targetPort: 9094
  # [podname].broker.kafka.svc.cluster.local
  clusterIP: None
  #type: NodePort
  selector:
    app: kafka
